version: '3.8'

services:
  postgis:
    build:
      context: .
      dockerfile: ./dockerfiles/postgis-arm.Dockerfile
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: gis
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: ./geodata
        target: /data
      

  neo4j:
    build:
      context: .
      dockerfile: ./dockerfiles/neo4j-arm.Dockerfile
    ports:
      - "7474:7474"
    volumes:
      - type: bind
        source: ./neo4j
        target: /data
      
      
